import Head from "next/head";
import Image from "next/image";
// import styles from "@/styles/Home.module.css";

export default function Home() {

  const numero = 42;
  const nome = "Luca";

  function raddoppia(numero) {
    return numero * 2;
  }

  const x = [1, 22, 333];
  const y = { nome: "Luca" };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello Next World!</h1>
        <h2>Benvenuto, {nome}</h2>
        <h3>Il tuo numero è {numero}</h3>
        <ul>
          <li>{raddoppia(2)}</li>
          <li>{raddoppia(4)}</li>
          <li>{raddoppia(8)}</li>
          <li>{raddoppia(16)}</li>
        </ul>
        <p>{x.join(", ")}</p>
      </div>
    </>
  );
}
