import Head from "next/head";
import Image from "next/image";
// import styles from "@/styles/Home.module.css";

export default function Home() {

  const numeri = [1, 2, 4, 8];

  function getNumbersList() {
    return numeri.map(numero => <li>{numero}</li>)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello Next World!</h1>
        <ul>{getNumbersList()}</ul>
      </div>
    </>
  );
}
